return {
  require("unicatevn.plugins.telescope"),
  require("unicatevn.plugins.nvim-treesitter"),
  require("unicatevn.plugins.nvim-treesitter-context"),
  require("unicatevn.plugins.nvim-treesitter-textobject"),
  -- require("unicatevn.plugins.nvim-tree"),
  require("unicatevn.plugins.oil"),
  require("unicatevn.plugins.harpoon"),
  require("unicatevn.plugins.hop"),
  require("unicatevn.plugins.comment"),
  require("unicatevn.plugins.lsp"),
  require("unicatevn.plugins.tokyo-night"),
  require("unicatevn.plugins.vim-fugitive"),
  require("unicatevn.plugins.autopairs"),
  require("unicatevn.plugins.trouble"),
  require("unicatevn.plugins.treesj"),
  require("unicatevn.plugins.dadbod"),
  'nvim-treesitter/playground',
  'windwp/nvim-ts-autotag',
  -- 'rafamadriz/neon',
  'github/copilot.vim',
}
